[package]
name = "tower-defense"
version = "1.0.0"
description = "A tower defense game"
authors = []
edition = "2021"

[lib]
name = "tower_defense_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
